/**
 * Created by michal on 30/09/16.
 */

var MODES = {
	GIFT_WRAPPING: false,
	GRAHAM_SCAN: false,
	TRIANGULATION_SWEEP_LINE: false,
	DIRECT_POINTS_SET: false,
	KD_TREE: false,
}

var MODES_SETTINGS = {
	GIFT_WRAPPING: "GIFT_WRAPPING",
	GRAHAM_SCAN: "GRAHAM_SCAN",
	TRIANGULATION_SWEEP_LINE: "TRIANGULATION_SWEEP_LINE",
	DIRECT_POINTS_SET: "DIRECT_POINTS_SET",
	KD_TREE: "KD_TREE",
}
