/**
 * Created by michal on 30/09/16.
 */

var MODES = {
	GIFT_WRAPPING: false,
	GRAHAM_SCAN: false,
	TRIANGULATION_SWEEP_LINE: false,
	TRIANGULATION_DELAUNAY: false,
	DIRECT_POINTS_SET: false,
	KD_TREE: false,
	VORONOI: false,
}

const MODES_SETTINGS = {
	GIFT_WRAPPING: "GIFT_WRAPPING",
	GRAHAM_SCAN: "GRAHAM_SCAN",
	TRIANGULATION_SWEEP_LINE: "TRIANGULATION_SWEEP_LINE",
	TRIANGULATION_DELAUNAY: "TRIANGULATION_DELAUNAY",
	DIRECT_POINTS_SET: "DIRECT_POINTS_SET",
	VORONOI: "VORONOI",
}
